### ISSUE TITLE
Track 240V double breaker with one CT

### ISSUE THREAD

**Issue by MarkBryanMilligan** [MarkBryanMilligan/LanternPowerMonitor#1]
Right now, each pole of a double pole breaker requires its own CT.  To save on the cost of current transformers, add a configuration variable so only the top breaker needs a CT and the power of the top pole is doubled in software.

**Comment by JamesAndrews352** [comment]
That would save some hardware for sure. Keep in mind some 240v loads may have a neutral and 120v loads like a stove/range, but yeah, most are balanced. I have a 30 space panel with 1 tandem breaker, so I like the idea. Save me from a third meter. Love your work!!

**Comment by MarkBryanMilligan** [comment]
Ok, thanks for that info.  That's why I decided to track both for now just to make sure it was accurate, I had a feeling some appliances might have unbalanced usage.  None of mine do, but it's good to know that it's a possible use case.  I think I'll make this a configuration option for the double breaker so those who need to track both poles individually will still be able to.

**Comment by dcsar1** [comment]
Another vote for this one.  I just ordered a couple of kits.  When the canoe from China (with the sensors) finally makes landfall I hope to set this up.

**Comment by MarkBryanMilligan** [comment]
It's kinda lame that GitHub doesn't have a voting system for issues.  What could that take to add, like an afternoon??  I always add a comment when adding an issue (and I would expect anyone else creating an issue to do the same).  I think we should use a thumbs up on that first description comment to count as a vote.  Then I should be able to visualize a little more easily what to do first.

**Comment by MarkBryanMilligan** [comment]
Ok, this one is done:
[Commit](https://github.com/MarkBryanMilligan/LanternPowerMonitor/commit/a75231dc437cc4e1e5b87e6aec084bac215a0ebe)

I'll leave this issue open until someone else verifies that it works, but I just tried it in my house on our heat pump and it seems to be working fine.  I'll push a new release to google play for the app, it should be available tomorrow.

In the panel config, you can now select "Double Pole (240V) Two CTs" or "Double Pole (240V) One CT Doubled"

**Comment by MarkBryanMilligan** [comment]
I saw when I close the other issue that I can reopen them if there ends up being a problem.  This change has been working fine in my has for the past couple days so I'm gonna go ahead and close the issue.
