### ISSUE TITLE
New software

### ISSUE THREAD

**Issue by desperateone** [MarkBryanMilligan/LanternPowerMonitor#12]
Your new software was updated today on my phone so I went to redo the double pole breakers. Before that I'm currently showing a need of 16 CT's. Which is for 240V double-poles, 2 tandem breakers and four singles. After redoing and selecting " Double Pole (240V) One CT Doubled " for the four 240V breakers. I'm still showing 16 brekers and a BOM still shows 16 breakers where I'm expecting it to now show 12 breakers and BOM of 12 CT's but it as if it hasn't changed, am I doing something wrong ? Or is it a bug ?

**Comment by MarkBryanMilligan** [comment]
Yeah, that's totally a bug.  I changed the software so the hubs would use the config to double the power for a single pole of a double breaker, but I haven't updated the BOM generation.  I'll fix that here and have a release out in a few hours.  Regardless of what the BOM generation does, the hubs will work just fine with one CT on a double pole if you configure it that way.

**Comment by MarkBryanMilligan** [comment]
I thought you had already ordered your CTs.  You made a rather threatening complaint a few days ago about how much you had spent on CTs.  Does this bug actually affect you in any way?

**Comment by MarkBryanMilligan** [comment]
I deployed a fix for this, it's live now.  Good luck.

**Comment by desperateone** [comment]
> I thought you had already ordered your CTs. You made a rather threatening complaint a few days ago about how much you had spent on CTs. Does this bug actually affect you in any way?

CT's coming from China, should be here by March 15th
