### ISSUE TITLE
[Android APP] - Add a 'shutdown' button

### ISSUE THREAD

**Issue by jeremyparks** [MarkBryanMilligan/LanternPowerMonitor#14]
I noticed when moving my pi there was no button to shut down.  It is better to shut down than just pull the plug to avoid data corruption.

**Comment by MarkBryanMilligan** [comment]
Just to clarify, you're saying add this as an action button on the hub page, so the phone can instruct the hub to shut down via bluetooth?  That shouldn't be too hard to add, I just want to make sure I have the workflow right.  I was thinking about maybe allowing the hubs to be pull commands from the service as it posts its data.  It'd be a little faster and less clunky than bluetooth, but I haven't built the framework for it yet.

**Comment by jeremyparks** [comment]
Yeah, got the idea from Octoprint. You can shutdown the pi from the
interface. Since the pi runs as headless it is nice to have the option to
shutdown (poweroff).

It would be similar to reboot that you already have.

**Comment by MarkBryanMilligan** [comment]
This is done.  Android app is released, hub software needs to be updated to 1.0.2 for it to work.  [Commit](https://github.com/MarkBryanMilligan/LanternPowerMonitor/commit/2a5674b736db4ad590bddd8b8e3cf99d29c3e48e)
