### ISSUE TITLE
Breaker counts inaccurate in Lantern software 

### ISSUE THREAD

**Issue by desperateone** [MarkBryanMilligan/LanternPowerMonitor#16]
An issue I brought up which you said would have been corrected with the last update is still with it. Using one CT per double pole breaker isn't showing the correct breaker count.

**Comment by MarkBryanMilligan** [comment]
The breaker counts are accurate.  Changing how you're monitoring your breakers does not change the actual number of breakers in your panel.  By monitoring two breakers with one CT, you're saving money by buying one fewer CT, but there are still 2 CTs in your panel.  The count is accurate.  Closing.
