### ISSUE TITLE
Firetab Bug

### ISSUE THREAD

**Issue by sicXnull** [MarkBryanMilligan/LanternPowerMonitor#21]
Heads up. Looks like there may be a potential bug when using this on the newest firetab. I keep getting the "turn on location services" error, despite them being on. 

![Screenshot_20211009-163857](https://user-images.githubusercontent.com/31908995/136673280-c0158032-0ea1-42dd-85a4-ad9468ab54ad.png)
![Screenshot_20211009-163948](https://user-images.githubusercontent.com/31908995/136673281-382201fa-70f4-48ff-b0f2-dcfbc12d91d0.png)

**Comment by MarkBryanMilligan** [comment]
Are you sure you have your location services on?  I see you've got bluetooth scanning on, but like the dialog says, android now requires the "use location" option to be turned on as well.  I don't understand android's reasoning behind it, and I don't have any control over it.

If you have location services on and it's still not working, then yeah, it might be a problem with the Firetab specifically.  Try turning on location services even before going in to add your hub.  If it still doesn't work, let me know and I'll try to get an emulator going to see if I can replicate it.

**Comment by sicXnull** [comment]
Unless I am missing something, i'm fairly sure every option is turned on. 

tbh i mainly just want to get it set up for hassio and grafana stats. Is it possible to set this up without configuring through the app? i added the MQTT info you listed [here](https://www.reddit.com/r/LanternPowerMonitor/comments/p7ssnp/comment/h9wwaw5/?utm_source=share&utm_medium=web2x&context=3), but my broker is still not receiving any data. no errors in debug 

![Screenshot_20211009-204447](https://user-images.githubusercontent.com/31908995/136677514-62ef1e7d-e31f-4eb4-92bc-9ac932d0a65f.png)
![Screenshot_20211009-205106](https://user-images.githubusercontent.com/31908995/136677515-7e86deb8-4391-4694-b638-59c8a405b2bd.png)
![Screenshot_20211009-204507](https://user-images.githubusercontent.com/31908995/136677516-37841a91-7049-4f5d-9012-ea7948b1b05f.png)
![Screenshot_20211009-204552](https://user-images.githubusercontent.com/31908995/136677517-53ecaea5-2a4e-402c-946f-bd9631290a51.png)
![Screenshot_20211009-205042](https://user-images.githubusercontent.com/31908995/136677518-90a75cac-68ab-4e83-b6e7-867acc425606.png)

**Comment by MarkBryanMilligan** [comment]
This is the block of code where I check if location services is enabled:

if ((locManager != null) && !locManager.isProviderEnabled(LocationManager.GPS_PROVIDER)) {
	dialog(R.string.location, R.string.location_request, ()->{
		Intent enableLocIntent = new Intent(Settings.ACTION_LOCATION_SOURCE_SETTINGS);
		startActivityForResult(enableLocIntent, ENABLE_LOC_REQUEST_CODE);
	}, this::finish);
	return;
}

Apparently on Amazon devices, I need to check for NETWORK_PROVIDER instead of GPS_PROVIDER.  I'll try to get a workaround added and released this week.  I think you'll be better off getting it configured in the app instead of messing around in json files.  If you get that working and use the actual app, I think you'll get a lot more out of the app than what Home Assistant can offer, but ideally you'll be able to use both.

**Comment by sicXnull** [comment]
Cool thanks! Ideally, I would like to use both.
