### ISSUE TITLE
iOS app crashed while adding new Hub

### ISSUE THREAD

**Issue by poisa** [MarkBryanMilligan/LanternPowerMonitor#28]
I'm adding a new hub and all goes as planned while adding the WIFI credentials. At that point it says that the Pi will restart but when it does, the app thinks this is a new hub and asks me to cancel, replace, or expand (I'm not sure what the last option is though). I first clicked Cancel and the app crashed. I then the app would not detect the hub anymore (and it wasn't listed anywhere). I rebooted the Pi and the process started again but tried "replace" this time. It crashed again. I sometimes see the hub and sometimes I don't, however I can reproduce the crashes consistently in the Hubs page.

Thanks for making the iOS app. It looks really promising! Can't wait to test my new monitor.

**Comment by MarkBryanMilligan** [comment]
When you're adding a hub for the first time, it should just ask you if you want to add it.  It should only be asking if you want to replace or expand if you already have a hub in your configuration (the expand option is to add a second, third, etc hub to your system if you need to monitor more than 15 breakers).  Did you add a hub previously using the android app?  If you already had it up and running on android, you shouldn't need to change the hub configuration at all.

To start from scratch on iOS, the hub will need to be running version 1.0.8 of the hub software.  I shipped all the kickstarter rewards with 1.0.7. You can download version 1.0.8 with this link:
https://cf.lanternpowermonitor.com/hub_1.0.8.zip
You'll need to take the SD card out of the hub and flash it with this new version using balena etcher (or an sd imaging software of your choice)

Regardless of what version of software the hub was running, or whether the hub had already been added via android, the iOS app shouldn't be crashing.  I'll admit, in my rush to get it released, I didn't test the scenario of connecting to a hub running 1.0.7 that had been previously configured with android.  While you're updating your hub software to 1.0.8, I'll try to replicate that scenario and see if I can get a fix released for the iOS app.  Thanks for letting me know!

**Comment by MarkBryanMilligan** [comment]
I also just noticed that you purchased two kits.  To keep things simple, I would try adopting one hub at a time (keep the second hub turned off until you adopt the first).  That's not technically necessary, but it can be a little hard to keep track of which hub you're adding otherwise.

**Comment by MarkBryanMilligan** [comment]
No, you can be logged into as many devices as you want, and switching from android to iOS even during setup shouldn't be a problem, it just ended up in a state that I didn't handle very well.  Thanks for finding this scenario, I'll get it handled in the next release of iOS and it'll save a lot of other people from experiencing the same headache!

**Comment by poisa** [comment]
Sounds good. You're welcome!

**Comment by MarkBryanMilligan** [comment]
Resolved in 1.0.9 of the iOS app.  (I forgot to close this back when I fixed it)
