### ISSUE TITLE
Create Raspberry Pi 4 image

### ISSUE THREAD

**Issue by MarkBryanMilligan** [MarkBryanMilligan/LanternPowerMonitor#3]
The current image only seems to work on a Pi 3 out of the box.  It can be made to work on the Pi 4 but you need to tweak some stuff on the command line.  It'd be easier for Pi 4 users to have an image that works without any modification.

**Comment by rharter** [comment]
Curious if there's any reason this can't work on a Zero.  The Zero W has a 40 pin header (no stock connector), and seems comparably speced to the 3A. And...it's $10. Event better, the original Zero 1.3 is $5 at [Adafruit](https://www.adafruit.com/product/2885), which is really attractive for something like this, which doesn't need USB hubs and HDMI ports.

**Comment by MarkBryanMilligan** [comment]
I kind of expect it to be CPU limited.  On a pi 3 A+ (or B+) with the quad core Cortex-A53 1.4 GHz, it gets about 300 samples per cycle.  On a 4 b+ with its quad core Cortex-A72 1.5 GHz, it gets about 400 samples per cycle.  A zero only has a single core and I keep one core pegged at 100% cpu 24/7 sampling the ADCs.  I thread off calculating the power and posting it to the server since there are other cores available for that work.  I have a feeling on a single core machine running java, the sampling would get all jacked up as garbage collection occurs during the computation and http call phase of each second.

**Comment by MarkBryanMilligan** [comment]
I made a new image that works on both pi 3s and pi 4s.  I also zipped it this time to make the download smaller.  The new image is [here](https://lanternsoftware.com:13781/hub_1.0.0.zip)

Closing this issue.
