### ISSUE TITLE
Provision for filtering caps on CT inputs to PCB

### ISSUE THREAD

**Issue by KodinLanewave** [MarkBryanMilligan/LanternPowerMonitor#35]
Per the conclusions found in the following analysis for popular CT's:
https://www.casler.org/wordpress/low-current-measurement-performance-of-the-sct013/
Adding a low-value ceramic capacitor on the input of each CT lowers the noise floor significantly;  Is it possible to add pad provisions to the PCB for users to add their own filter caps?
Going a step further, I'd also love a revision of the board where one can modify the ring/shield connections to allow proper grounding of the shield and input from the ring contact for each CT.  This would require re-soldering of each CT's connector, however further improve the noise-floor of these devices.  Obviously this would mean the wiring is fully incompatible with un-modified CT's, unless there were also jumpers added to switch inputs as needed.  Just a few thoughts, and something I'd appreciate having the option for.

**Comment by sodabrew** [comment]
Filtering caps mentioned in https://github.com/MarkBryanMilligan/LanternPowerMonitor/issues/29 as well, to keep the conversation together

**Comment by KodinLanewave** [comment]
Sorry about that, I should probably close this one out and add on to the existing issue.

**Comment by KodinLanewave** [comment]
Closing as a duplicate to #29
