### ISSUE TITLE
Image Password

### ISSUE THREAD

**Issue by LeoLopesLage** [MarkBryanMilligan/LanternPowerMonitor#37]
Hi, just downloaded the Hub_1.0.8 image file.

When flashing it to the SD Card, it asks for a password.
I used the one in the readme.md "The default password on this image is pi/LanternPowerMonitor", but it says it's wrong and doesn't flash the card.

Can you help me?

**Comment by MarkBryanMilligan** [comment]
What SD imaging software are you using?  There isn't a password on the image itself, the pi/LanternPowerMonitor credentials are for the linux OS that gets installed onto the SD card, so after you start up the pi you can ssh into it and poke around.

This is probably an issue with the SD imaging software, or the image that you downloaded.  The hub_1.0.8.img file (after unzipping it) should be 3,164,582,400 bytes so you might want to make sure you have the complete download.

**Comment by LeoLopesLage** [comment]
Thanks. Problem solved. Downloaded again and it worked. Go figure it out..
