### ISSUE TITLE
SD card download link broken

### ISSUE THREAD

**Issue by zyphlar** [MarkBryanMilligan/LanternPowerMonitor#50]
Cloudflare is currently giving an error when downloading, but archive.org has it: https://web.archive.org/web/20221226174130/https://cf.lanternpowermonitor.com/hub_1.1.1.zip

Thanks for all that you do, I love this project and hope to see it continue!

**Comment by MarkBryanMilligan** [comment]
Oops, yeah I let the SSL certificate expire on the apache box that's behind all of that.  I just updated it and changed the link to the most recent version https://cf.lanternpowermonitor.com/hub_1.1.3.zip

Thanks for letting me know that was down!
